### ISSUE TITLE
Crash on adding a container

### ISSUE THREAD

**Issue by andreaferretti** [tailhook/vagga#180]
Hi, I was trying to make a container for launching scala notebooks using ipython/jupyter.

Everything goes well adding scala dependencies and ipython itself. But as soon as I try to make a child container to run iscala, vagga crashes. The vagga file looks like

```yaml
containers:
  jvm:
    setup:
    - !UbuntuRelease { version: 15.04 }
    - !UbuntuUniverse
    - !Install [openjdk-8-jre-headless, ca-certificates]
  sbt:
    setup:
    - !Container jvm
    - !Install [curl]
    - !EnsureDir /work/.home/sbt
    - !Download
      url: https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt
      path: /work/.home/sbt/sbt
      mode: 0o744
    - !Sh "sed -i '/^root/{s@/root@/work/.home@;}' /etc/passwd"
    volumes:
      /tmp: !Tmpfs
      size: 100Mi
      mode: 0o1777
    environ:
      PATH: "/work/.home/sbt:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: /work/.home
  jupyter:
    setup:
    - !Container sbt
    - !PipConfig
      dependencies: true
    - !Py3Install ["ipython[notebook]==2.4.1"]
  iscala:
    setup:
    - !Container jupyter
commands:
  scala: !Command
    container: sbt
    run: sbt -sbt-create console
    description: Run a scala console
  sbt: !Command
    container: sbt
    run: [sbt]
    description: Run sbt
  iscala: !Command
    container: iscala
    run: bash
    description: Run a scala notebook
  sh: !Command
    container: sbt
    run: bash
    description: Enter a shell with sbt available
```

Even just adding the `iscala` container depending on `jupyter` is enough to trigger the crash.

To reproduce the crash, run `vagga iscala` on latest `vagga-testing'. The error I get is

```
papillon@marvin:~/esperimenti/vagga/scala$ vagga iscala
ERROR:vagga::wrapper: Error executing _build: Builder killed by signal SIGSEGV[11] (core dumped)
Command <Command "/proc/self/exe" ("vagga_wrapper") "_build" "iscala"; environ: {"_VAGGA_HOME"="/home/papillon","TERM"="xterm","RUST_LOG"="warn",}; uid_map=[UidMap { inside_uid: 0, outside_uid: 1000, count: 1 }, UidMap { inside_uid: 100000, outside_uid: 100000, count: 65536 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1000, count: 1 }, GidMap { inside_gid: 100000, outside_gid: 100000, count: 65536 }]> exited with code 124
```

**Comment by lilianmoraru** [comment]
@andreaferretti Could you please run the same command but with `RUST_BACKTRACE=1` and put the output here?
Ex: `RUST_BACKTRACE=1 vagga iscala`

Are you using vagga stable? If yes, can you try with the latest vagga testing(there was a similar issue before).

**Comment by andreaferretti** [comment]
I am using `vagga-testing`. I tried running the command as you mentioned, but I just get

```
papillon@aureliano:~/esperimenti/vagga/scala$ RUST_BACKTRACE=1 vagga iscala
ERROR:vagga::wrapper: Error executing _build: Builder killed by signal SIGSEGV[11] (core dumped)
Command <Command "/proc/self/exe" ("vagga_wrapper") "_build" "iscala"; environ: {"RUST_BACKTRACE"="1","RUST_LOG"="warn","_VAGGA_HOME"="/home/papillon","TERM"="xterm",}; uid_map=[UidMap { inside_uid: 0, outside_uid: 1000, count: 1 }, UidMap { inside_uid: 100000, outside_uid: 100000, count: 65536 }]; gid_map=[GidMap { inside_gid: 0, outside_gid: 1000, count: 1 }, GidMap { inside_gid: 100000, outside_gid: 100000, count: 65536 }]> exited with code 124
```

Let me know if I can add any information. If you want to tinker yourself, just copying the `vagga.yaml` above and running `vagga iscala` should reproduce the error

**Comment by lilianmoraru** [comment]
@andreaferretti Ye, I just tried it myself and I got nothing too.

Would be strange if it again because of the small `musl` stack size because copying containers has been done a lot of times before that...

**Comment by tailhook** [comment]
Yes. Probably probably it's deep nesting of containers which triggers bug with small stack size in musl. I'll be on vacation up to the end of next week, so I'm not sure I can fix it soon.

In the meantime, reducing nesting should fix the problem. Just put all the steps in the one/two containers. Usually, you don't need such deep nesting. For documentation purposes, you can insert arbitrary number of comments between steps.

**Comment by andreaferretti** [comment]
In general there is a pretty good reason for nesting: building containers takes a little experimentation, and once I get a working component, I usually freeze it and nest a container to start working on the next part. At the end, I should be able to compress it to a few steps, but nesting is a giant time-saver.

Thank you anyway for your very quick help! For now I will try to avoid nesting too much, but it would be nice not to have to worry for that :-)

**Comment by tailhook** [comment]
Sure. I'll fix the issue. You should note, however, that each container takes disk space.

Another pattern for experimentation is just split with static, and experimentation part. Moving steps from one container to another. But, yes, this is just a little bit uglier :)

**Comment by andreaferretti** [comment]
Great! By the way, are there any plans to use a layered filesystem, such as what Docker uses? It is just a space optimization, nothing really fundamental since Vagga keeps the nesting much more limited, but it may be nice eventually

**Comment by tailhook** [comment]
@andreaferretti we don't have too much options because of using user namespaces. Basically there are two options:

1. Use overlayfs with a patch (which is included in Ubuntu kernel by default)
2. Use layers only on btrfs

The issue with (1) is that it requires a patch (the stock kernel doesn't support overlayfs by non-privileged user). And there is no ready to use kernel with the patch for nixos (which I use for everyday work).

With btrfs the problem is that you can *create* a snapshot by unprivileged user by you can't *delete* a snapshot, unless a special option is passed to a mount point. Alternatively, the reflinking can be used instead of snapshots, but that saves disk space (and a little bit time) for the files in the data, but not for copying file metadata itself (like directories and files). So for some containers it will not give much performance gains. 

Anyway, I plan to experiment with both things.

**Comment by tailhook** [comment]
Okay, I think I've fixed it. You need vagga at least `v0.4.1-152-gd026352` (still building in buildbot)

There is a test for 10 nested containers. The limit is about 13 for now (unfortunately, it also depends on which commands are used and which commands are present in vagga at all, probably will find better fix later).

**Comment by andreaferretti** [comment]
Great work! :-)

**Comment by andreaferretti** [comment]
I am still getting this error, even without too much nesting. For instance, I have a `vagga.yaml` file with a maximum nesting level of 4 that still triggers the error (running vagga-testing on Ubuntu).

I include the file here - it is a little long, but the nesting is limited to 4 levels. The error appears with either `play` or `akka-http`. I am sorry I cannot include everything, since the project is not open source yet.

```yaml
containers:
  base:
    setup:
    - !UbuntuRelease { version: 15.04 }
    - !UbuntuUniverse
  wrk:
    setup:
    - !Container base
    - !AptTrust keys: [5BB92C09DB82666C]
    - !UbuntuPPA fkrull/deadsnakes
    - !Install [build-essential, libssl-dev, python3.5]
    - !Git
      url: https://github.com/wg/wrk.git
      path: /opt/wrk
    - !Sh |
        cd /opt/wrk
        make
    - !PipConfig
      install-python: false
      python-exe: python3.5
      dependencies: true
    - !Py3Install [requests]
    environ:
      PATH: "/opt/wrk:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  jvm:
    setup:
    - !Container base
    - !Install [openjdk-8-jdk, ca-certificates]
  sbt:
    setup:
    - !Container jvm
    - !Install [curl, unzip]
    - !EnsureDir /work/.home/sbt
    - !Download
      url: https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt
      path: /work/.home/sbt/sbt
      mode: 0o744
    - !Sh "sed -i '/^root/{s@/root@/work/.home@;}' /etc/passwd"
    volumes:
      /tmp: !Tmpfs
      size: 100Mi
      mode: 0o1777
  nim:
    setup:
    - !Container base
    - !Install [build-essential, git, ca-certificates]
    - !Env NIM: /opt/nim
    - !Sh |
        git clone https://github.com/nim-lang/Nim.git $NIM
        cd $NIM
        git clone --depth 1 https://github.com/nim-lang/csources
        cd csources
        sh build.sh
        cd ..
        bin/nim c koch
        ./koch boot -d:release -d:useGnuReadline
    - !Env
      HOME: /work/.home
      PATH: "/work/.home/.nimble/bin:/opt/nim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    - !Sh |
        git clone https://github.com/nim-lang/nimble.git
        cd nimble
        git clone -b v0.13.0 --depth 1 https://github.com/nim-lang/nim vendor/nim
        nim c -r src/nimble install
    - !Remove /work/nimble
  jester:
    setup:
    - !Container nim
    - !Depends frameworks/jester/web.nim
    - !Sh |
        cd frameworks/jester
        nimble c -d:release web
    environ:
      PATH: "/work/.home/.nimble/bin:/opt/nim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: /work/.home
  nim-async-http:
    setup:
    - !Container nim
    - !Depends frameworks/nim-async-http/web.nim
    - !Sh |
        cd frameworks/nim-async-http
        nim c -d:release web
    environ:
      PATH: "/work/.home/.nimble/bin:/opt/nim/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: /work/.home
  play:
    setup:
      - !Container sbt
      - !Depends frameworks/play-netty
      - !Sh |
          cd frameworks/play-netty
          sbt update
    environ:
      PATH: "/work/.home/sbt:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: /work/.home
  akka-http:
    setup:
      - !Container sbt
      - !Depends frameworks/akka-http
      - !Sh |
          cd frameworks/akka-http
          sbt update
    environ:
      PATH: "/work/.home/sbt:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      HOME: /work/.home
commands:
  wrk: !Command
    container: wrk
    run: [wrk]
    description: Run wrk
  benchmark: !Command
    container: wrk
    run: [./harness.py]
    work-dir: /work/scripts
    description: Run benchmarks
  play: !Command
    container: play
    run: sbt run
    work-dir: /work/frameworks/play-netty
    description: Run Play! framework
  akka-http: !Command
    container: akka-http
    run: sbt run
    work-dir: /work/frameworks/akka-http
    description: Run Akka HTTP framework
  jester: !Command
    container: jester
    run: /work/frameworks/jester/web
    description: Run Jester framework
  nim-async-http: !Command
    container: nim-async-http
    run: /work/frameworks/nim-async-http/web
    description: Run bare async-http Nim application
```

**Comment by tailhook** [comment]
@andreaferretti, thanks for the report, I'll take a look. Could you confirm which version of vagga do you use?

**Comment by andreaferretti** [comment]
```
vagga --version
v0.4.1-131-g6820734
```

**Comment by tailhook** [comment]
@andreaferretti you need a newer version. The new one not only allows more deeply nested containers, but also dramatically decreased stack usage, so other stack-size-related crashes are also gone.

**Comment by andreaferretti** [comment]
Uhm... is it published on vagga-testing? I thought that repo was synced to master

**Comment by tailhook** [comment]
http://files.zerogw.com/vagga/latest-testing.html -- shows vagga-0.4.1-157-gce94fa0.tar.xz, something wrong with ubuntu repo?

**Comment by tailhook** [comment]
Actually, I'm pretty sure that ubuntu repo is recent enough because we experienced similar crashes on our CI, which has vagga installed from ubuntu repo.

**Comment by andreaferretti** [comment]
Soryy, my fault. It seems my vagga was not updated, even though I had just updated the system.

It seems to work fine now for me - I am closing the ticket. Thank you, as usual
